version: '2'
services:
  web:
    image: ${REGISTRY_URL}/stockportwebapp:${TAG}
    ports:
      - 80:5000
    environment:
      - VIRTUAL_HOST=*.dbdtest.stockport.gov.uk,content
      - BUSINESS_ID
    external_links:
      - app_api_1:content
