version: '2'
services:
  web:
    image: ${REGISTRY_URL}/stockportwebapp:${TAG}
    environment:
      - VIRTUAL_HOST=*.healthystockport.co.uk
      - BUSINESS_ID
      - AUTH_PASSWORD
    links:
      - content
