version: '2'
services:
  web:
    image: devquay.stockport.gov.uk:5000/stockportwebapp
    ports:
      - 80:5000
    environment:
      - VIRTUAL_HOST=*.dbdtest.stockport.gov.uk,content
    external_links:
      - app_api_1:content
